services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: books_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - MONGODB_URL=mongodb://mongo_admin:password@mongo:27017

volumes:
  mongo_data: